#!/usr/bin/env python3
"""
Reads spec/schemas/*.schema.json and generates
src/ai_sdlc/core/_generated_schemas.py so schemas are inlined at build time.
"""

import json
import re
import textwrap
from pathlib import Path

SCHEMA_DIR = Path(__file__).resolve().parent.parent.parent / "spec" / "schemas"
OUTPUT = Path(__file__).resolve().parent.parent / "src" / "ai_sdlc" / "core" / "_generated_schemas.py"


def to_snake_case(filename: str) -> str:
    """'agent-role.schema.json' → 'agent_role_schema'"""
    name = filename.replace(".schema.json", "").replace("-", "_")
    return f"{name}_schema"


def main() -> None:
    files = sorted(SCHEMA_DIR.glob("*.schema.json"))
    if not files:
        raise RuntimeError(f"No schema files found in {SCHEMA_DIR}")

    lines = [
        '# AUTO-GENERATED by scripts/generate_schemas.py — do not edit manually.',
        '# ruff: noqa',
        '',
        'from __future__ import annotations',
        '',
        'from typing import Any',
        '',
    ]

    var_names: list[str] = []
    map_entries: list[str] = []

    for f in files:
        content = json.loads(f.read_text())
        var_name = to_snake_case(f.name)
        var_names.append(var_name)
        lines.append(f"{var_name}: dict[str, Any] = {json.dumps(content, indent=2)}")
        lines.append("")
        map_entries.append(f'    "{f.name}": {var_name},')

    lines.append("SCHEMAS: dict[str, dict[str, Any]] = {")
    lines.extend(map_entries)
    lines.append("}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUTPUT} ({len(files)} schemas)")


if __name__ == "__main__":
    main()
