/**
 * RFC-0025 §13 OQ-5 — operator-initiated upstream bug reporting.
 * Phase 6 (AISDLC-307).
 *
 * Builds a pre-filled GitHub issue URL for a `framework-misbehaved`
 * capture record so the operator can review + submit upstream. There is
 * NO telemetry pipeline: the report is pull-based, fully transparent,
 * and the operator's editor/browser is the final gate.
 *
 * Industry parallel: `bun --report-bug`, VS Code "Report Issue", Rust
 * panic handler's "consider reporting at github.com/...".
 *
 * Flow:
 *   1. Load capture record from `$ARTIFACTS_DIR/_quality/captures.jsonl`
 *      by capture id (synthesised as `<subclass>-<tsSlug>` to match the
 *      router's task-id convention) or by the same task-id-shaped slug
 *      the framework auto-generates.
 *   2. Render the issue body from `.ai-sdlc/templates/framework-bug-report.md`
 *      (ships at repo root; adopters customise per their conventions).
 *   3. Anonymise the body: strip absolute paths, env-style secrets, and
 *      reduce stderr noise to the framework-relevant tail.
 *   4. Build the GitHub URL: `<repoUrl>/issues/new?title=…&body=…`.
 *   5. Optionally open the URL in the default browser via `open(1)` /
 *      `xdg-open(1)` / `start` — caller controls via `openInBrowser`.
 *
 * Composes with the RFC-0024 capture-then-submit lifecycle pattern: this
 * is "submit upstream" instead of "submit team-internal".
 *
 * @module tui/analytics/upstream-reporter
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { spawn } from 'node:child_process';

import type { FrameworkBugCaptureRecord } from './quality-classifier.js';
import { FRAMEWORK_QUALITY_DIRNAME, FRAMEWORK_QUALITY_CAPTURES_FILE } from './quality-reader.js';
import { resolveArtifactsDir } from '../sources/types.js';
import { DEFAULT_UPSTREAM_TEMPLATE_PATH } from './quality-monitoring-config.js';

// ── Constants ─────────────────────────────────────────────────────────

/**
 * Re-exported default template path. Owner of the constant is
 * `quality-monitoring-config.ts` (Phase 6 config schema) so adopters
 * have one canonical source.
 */
export { DEFAULT_UPSTREAM_TEMPLATE_PATH } from './quality-monitoring-config.js';

/**
 * Built-in fallback template (used when the on-disk template is missing).
 * Keeps the reporter usable in fresh worktrees / minimal scaffolds.
 */
export const BUILTIN_UPSTREAM_TEMPLATE = [
  '## Framework bug — {{subclass}}',
  '',
  '**Severity:** {{severity_composite}} (operator-time-cost={{severity_otc}}, blast={{severity_blast}}, frequency={{severity_freq}})',
  '**Subclass:** `{{subclass}}`',
  '**Reported at (capture):** {{ts}}',
  '',
  '### Rationale (classifier output)',
  '',
  '{{rationale}}',
  '',
  '### Suggested fix',
  '',
  '{{suggested_fix}}',
  '',
  '### Related code paths',
  '',
  '{{related_paths}}',
  '',
  '### Anonymised repro',
  '',
  '```',
  'exit code: {{exit_code}}',
  'source:    {{source}}',
  '',
  '{{stderr_tail}}',
  '```',
  '',
  '---',
  '',
  '_This issue was pre-generated by `cli-quality report-upstream` (RFC-0025 §13 OQ-5)._',
  '_The operator reviewed and submitted this report. No automatic telemetry was transmitted._',
].join('\n');

// ── Capture loader ────────────────────────────────────────────────────

export interface LoadCaptureOpts {
  /** Override the artifacts dir; defaults to `$ARTIFACTS_DIR` or `./artifacts`. */
  artifactsDir?: string;
}

/**
 * Synthesise the capture id used to address a record. Mirrors the
 * router's task-id convention (`framework-bug-<subclass>-<tsSlug>`)
 * but accepts the short variant (`<subclass>-<tsSlug>`) too.
 */
export function buildCaptureId(record: FrameworkBugCaptureRecord): string {
  const tsSlug = record.ts.replace(/[^0-9T]/g, '').slice(0, 15);
  const subclassSlug = record.subclass.replace(/[^a-z0-9-]/g, '-').replace(/^-+|-+$/g, '');
  return `framework-bug-${subclassSlug}-${tsSlug}`;
}

/**
 * Load a capture record by id. The id may be the full router-shape
 * (`framework-bug-<subclass>-<tsSlug>`) or the short form
 * (`<subclass>-<tsSlug>`). Returns `null` when not found.
 */
export function loadCaptureRecord(
  bugId: string,
  opts: LoadCaptureOpts = {},
): FrameworkBugCaptureRecord | null {
  const artifactsDir = resolveArtifactsDir({ artifactsDir: opts.artifactsDir });
  const path = join(artifactsDir, FRAMEWORK_QUALITY_DIRNAME, FRAMEWORK_QUALITY_CAPTURES_FILE);
  if (!existsSync(path)) return null;

  let raw: string;
  try {
    raw = readFileSync(path, 'utf8');
  } catch {
    return null;
  }

  const wantFull = bugId.startsWith('framework-bug-') ? bugId : `framework-bug-${bugId}`;

  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    let parsed: FrameworkBugCaptureRecord;
    try {
      parsed = JSON.parse(line) as FrameworkBugCaptureRecord;
    } catch {
      continue;
    }
    const id = buildCaptureId(parsed);
    if (id === wantFull) return parsed;
  }
  return null;
}

// ── Anonymisation ─────────────────────────────────────────────────────

/**
 * Patterns that strip operator-identifying noise from stderr / source
 * fields before they ride into a GitHub issue body. Conservative — we
 * prefer leaving useful framework signal over leaking adopter context.
 *
 * Applied in order:
 *   1. Replace absolute home paths (`/Users/<name>/…`, `/home/<name>/…`)
 *      with `~/…` so the operator's username doesn't leak.
 *   2. Replace `<workDir>/.worktrees/<task-id>/` with `<worktree>/`.
 *   3. Replace common secret-shaped strings (`sk-…`, `ghp_…`, `xoxb-…`)
 *      with `<REDACTED-TOKEN>`.
 *   4. Replace email addresses with `<REDACTED-EMAIL>`.
 */
export function anonymiseText(input: string): string {
  if (!input) return input;
  return input
    .replace(/\/(?:Users|home)\/[^/\s]+/g, '~')
    .replace(/\/[^/\s]+\/\.worktrees\/[^/\s]+/g, '<worktree>')
    .replace(/\bsk-[A-Za-z0-9_-]{20,}\b/g, '<REDACTED-TOKEN>')
    .replace(/\bghp_[A-Za-z0-9_]{20,}\b/g, '<REDACTED-TOKEN>')
    .replace(/\bxox[bpasr]-[A-Za-z0-9-]{10,}\b/g, '<REDACTED-TOKEN>')
    .replace(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g, '<REDACTED-EMAIL>');
}

// ── Suggested-fix + related-paths heuristics ──────────────────────────

/**
 * Heuristic suggested-fix text per framework subclass. Returns the
 * matching playbook hint, or a generic "open the playbook" fallback.
 *
 * These hints are intentionally short — the upstream issue body links
 * to the playbook for full context; this gives maintainers a starting
 * point in the first scan of the issue.
 */
export function suggestFixForSubclass(subclass: string): string {
  const HINTS: Record<string, string> = {
    'framework-contract-violated':
      'Inspect Step 6 (parse-dev-return) JSON-envelope retry path. Likely fix: tighten the developer-side prompt or add a richer schema-error round-trip.',
    'framework-sweep-incomplete':
      'Inspect cleanup hooks (worktree teardown + `.active-task` sweep). Likely fix: ensure `cleanup()` runs in a `finally` for the failure path it missed.',
    'framework-silent-failure':
      'Inspect the pre-dispatch filter chain. Likely fix: replace `catch { /* ignore */ }` with explicit logging + re-throw or surface the failure to the operator.',
    'framework-coverage-gap':
      'No playbook handler matched. Likely fix: add a new handler in `pipeline-cli/src/orchestrator/playbook/handlers/` and a regression test that pins the new signal.',
    'framework-perf-regression':
      'Compare the operation against its `_quality/baselines/` baseline. Likely fix: identify the regression commit + revert or guard the slow path.',
    'framework-determinism-violated':
      'Compare the two dispatch outputs (`_quality/determinism/<task-id>.json`). Likely fix: pin the non-determinism source (timestamps, ordering, model temperature).',
    'framework-gate-faulty':
      'Audit the gate that passed/failed unexpectedly. Likely fix: tighten the predicate or add a regression test that captures the missed case.',
  };
  return (
    HINTS[subclass] ??
    'No automatic suggestion for this subclass. Inspect the rationale + original-failure block above and the relevant playbook handler.'
  );
}

/**
 * Heuristic related-code-paths per framework subclass. Returns a
 * short bulleted list maintainers can jump to. Subclasses outside the
 * built-in set get a generic pointer.
 */
export function relatedPathsForSubclass(subclass: string): string {
  const PATHS: Record<string, string[]> = {
    'framework-contract-violated': [
      '- `pipeline-cli/src/steps/06-dispatch-developer.ts` (Step 6 dispatch + JSON parse)',
      '- `pipeline-cli/src/orchestrator/playbook/handlers/handler-developer-json-contract-violated.ts`',
    ],
    'framework-sweep-incomplete': [
      '- `pipeline-cli/src/steps/13-cleanup.ts` (Step 13 cleanup)',
      '- `pipeline-cli/src/orchestrator/playbook/handlers/handler-cleanup-failed.ts`',
    ],
    'framework-silent-failure': [
      '- `pipeline-cli/src/orchestrator/admission/` (pre-dispatch filter chain)',
      '- `pipeline-cli/src/orchestrator/loop.ts` (tick orchestrator)',
    ],
    'framework-coverage-gap': [
      '- `pipeline-cli/src/orchestrator/playbook/handlers/` (handler registry)',
      '- `pipeline-cli/src/orchestrator/playbook/dispatch.ts` (handler-no-match path)',
    ],
    'framework-perf-regression': [
      '- `pipeline-cli/src/orchestrator/loop.ts` (tick timing)',
      '- `_quality/baselines/` (perf baseline corpus)',
    ],
    'framework-determinism-violated': [
      '- `pipeline-cli/src/tui/analytics/determinism-detector.ts`',
      '- `_quality/determinism/<task-id>.json` (stored baseline)',
    ],
    'framework-gate-faulty': [
      '- `pipeline-cli/src/dor/` (DoR gate)',
      '- `pipeline-cli/src/verifier/` (attestation gate)',
    ],
  };
  const paths = PATHS[subclass] ?? ['- (no built-in path mapping — inspect the rationale above)'];
  return paths.join('\n');
}

// ── Template rendering ────────────────────────────────────────────────

export interface RenderIssueBodyOpts {
  /** Project root used to locate the template. Defaults to cwd. */
  workDir?: string;
  /** Override the template path (relative to workDir or absolute). */
  templatePath?: string;
}

/**
 * Render the GitHub issue body from a capture record + a template.
 * The template is read from `<workDir>/<templatePath>` (default
 * `.ai-sdlc/templates/framework-bug-report.md`); missing template falls
 * back to `BUILTIN_UPSTREAM_TEMPLATE` so the reporter never crashes on
 * a fresh worktree.
 *
 * Supported placeholders (all anonymised):
 *   {{subclass}}, {{ts}}, {{rationale}}, {{exit_code}}, {{source}},
 *   {{stderr_tail}}, {{severity_composite}}, {{severity_otc}},
 *   {{severity_blast}}, {{severity_freq}}, {{suggested_fix}},
 *   {{related_paths}}, {{task_id}}, {{worker_id}}
 *
 * Unknown placeholders are left in place verbatim so adopters can extend
 * the template without breaking on render.
 */
export function renderIssueBody(
  record: FrameworkBugCaptureRecord,
  opts: RenderIssueBodyOpts = {},
): string {
  const workDir = opts.workDir ?? process.cwd();
  const templatePath = opts.templatePath ?? DEFAULT_UPSTREAM_TEMPLATE_PATH;
  const fullPath =
    templatePath.startsWith('/') || /^[A-Za-z]:\\/.test(templatePath)
      ? templatePath
      : join(workDir, templatePath);

  let template = BUILTIN_UPSTREAM_TEMPLATE;
  if (existsSync(fullPath)) {
    try {
      template = readFileSync(fullPath, 'utf8');
    } catch {
      template = BUILTIN_UPSTREAM_TEMPLATE;
    }
  }

  const stderr = anonymiseText(record.auditTrail.originalFailure.stderr ?? '');
  // Reduce noise: last 30 lines of stderr is usually the framework-relevant tail.
  const stderrTail = stderr.split('\n').slice(-30).join('\n').slice(0, 2000) || '(no stderr)';
  const source = anonymiseText(record.auditTrail.originalFailure.source ?? 'n/a');

  const values: Record<string, string> = {
    subclass: record.subclass,
    ts: record.ts,
    rationale: anonymiseText(record.auditTrail.classificationResult.rationale ?? ''),
    exit_code: String(record.auditTrail.originalFailure.exitCode ?? 'n/a'),
    source,
    stderr_tail: stderrTail,
    severity_composite: record.severity.composite,
    severity_otc: record.severity.axes.operatorTimeCost,
    severity_blast: record.severity.axes.blastRadius,
    severity_freq: record.severity.axes.frequency,
    suggested_fix: suggestFixForSubclass(record.subclass),
    related_paths: relatedPathsForSubclass(record.subclass),
    task_id: record.taskId ?? '(none)',
    worker_id: record.workerId ?? '(none)',
  };

  return template.replace(/\{\{([a-z_]+)\}\}/g, (match, key: string) => {
    if (Object.prototype.hasOwnProperty.call(values, key)) return values[key] ?? '';
    return match;
  });
}

// ── URL builder ───────────────────────────────────────────────────────

/**
 * Result of preparing an upstream report. `url` is the
 * `<repoUrl>/issues/new?title=…&body=…` URL the operator can paste
 * into a browser; `title` and `body` are the rendered pieces for
 * inspection / CLI display.
 */
export interface UpstreamReport {
  url: string;
  title: string;
  body: string;
  /** The capture id resolved from the input (full router-shape). */
  captureId: string;
}

export interface BuildUpstreamReportOpts extends RenderIssueBodyOpts, LoadCaptureOpts {
  /** Upstream repo URL (e.g. `https://github.com/org/repo`). Required. */
  repoUrl: string;
}

export class UpstreamReportError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'UpstreamReportError';
  }
}

/**
 * Build the pre-filled GitHub issue URL for a capture id.
 *
 * @throws UpstreamReportError when the capture id cannot be found or
 *   when `repoUrl` is empty.
 */
export function buildUpstreamReport(bugId: string, opts: BuildUpstreamReportOpts): UpstreamReport {
  if (!opts.repoUrl || !opts.repoUrl.trim()) {
    throw new UpstreamReportError(
      'repoUrl is required — set `quality.upstream-reporting.repoUrl` in `.ai-sdlc/quality-monitoring.yaml` or pass --repo-url',
    );
  }

  const record = loadCaptureRecord(bugId, { artifactsDir: opts.artifactsDir });
  if (!record) {
    throw new UpstreamReportError(
      `capture not found for bug id '${bugId}'. Check $ARTIFACTS_DIR/_quality/captures.jsonl and 'cli-quality-corpus aggregate --format table'.`,
    );
  }

  const title = `Framework bug: ${record.subclass} (${record.severity.composite} severity)`;
  const body = renderIssueBody(record, {
    workDir: opts.workDir,
    templatePath: opts.templatePath,
  });
  const captureId = buildCaptureId(record);

  // Strip trailing slash from repoUrl so we always emit one clean separator.
  const base = opts.repoUrl.trim().replace(/\/+$/, '');
  const url = `${base}/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`;

  return { url, title, body, captureId };
}

// ── Browser open ──────────────────────────────────────────────────────

export interface OpenInBrowserOpts {
  /** Override for tests / non-interactive environments. */
  spawnFn?: (cmd: string, args: string[]) => { unref: () => void };
}

/**
 * Open a URL in the default browser using the OS-native opener
 * (`open` on macOS, `xdg-open` on Linux, `start` on Windows). Detached
 * + unref'd so the CLI exits cleanly afterwards.
 *
 * Returns `true` on dispatch, `false` on unsupported platform / spawn
 * failure. Errors are swallowed — the URL is also printed to stdout by
 * the caller, so the operator can always copy-paste as a fallback.
 */
export function openInBrowser(url: string, opts: OpenInBrowserOpts = {}): boolean {
  const platform = process.platform;
  let cmd: string;
  let args: string[];
  if (platform === 'darwin') {
    cmd = 'open';
    args = [url];
  } else if (platform === 'win32') {
    cmd = 'cmd';
    args = ['/c', 'start', '', url];
  } else {
    // linux / freebsd / other unix
    cmd = 'xdg-open';
    args = [url];
  }

  try {
    const spawnFn =
      opts.spawnFn ??
      ((c, a): { unref: () => void } => {
        const child = spawn(c, a, { detached: true, stdio: 'ignore' });
        return { unref: (): void => child.unref() };
      });
    const handle = spawnFn(cmd, args);
    handle.unref();
    return true;
  } catch {
    return false;
  }
}
