/**
 * Reads spec/schemas/*.schema.json and generates src/core/generated-schemas.ts
 * so schemas are inlined at build time — no fs.readFileSync at runtime.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMA_DIR = resolve(__dirname, '../../spec/schemas');
const OUTPUT = resolve(__dirname, '../src/core/generated-schemas.ts');

function toCamelCase(filename: string): string {
  // "agent-role.schema.json" → "agentRoleSchema"
  return (
    filename.replace('.schema.json', '').replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()) +
    'Schema'
  );
}

const files = readdirSync(SCHEMA_DIR)
  .filter((f) => f.endsWith('.schema.json'))
  .sort();

const exports: string[] = [];
const mapEntries: string[] = [];

for (const file of files) {
  const content = readFileSync(resolve(SCHEMA_DIR, file), 'utf-8');
  const varName = toCamelCase(file);
  exports.push(`export const ${varName} = ${content.trimEnd()} as const;\n`);
  mapEntries.push(`  '${file}': ${varName},`);
}

const output = `// AUTO-GENERATED by scripts/generate-schemas.ts — do not edit manually.

${exports.join('\n')}
export const SCHEMAS: Record<string, object> = {
${mapEntries.join('\n')}
};
`;

writeFileSync(OUTPUT, output, 'utf-8');
console.log(`Generated ${OUTPUT} (${files.length} schemas)`);
