export {
  deterministicPort,
  allocatePort,
  allocateContiguousPorts,
  isPortFree,
  PortAllocationError,
  DEFAULT_BASE_PORT,
  PORT_RANGE_OFFSET_MIN,
  PORT_RANGE_OFFSET_MAX,
  type AllocatePortOptions,
  type AllocateContiguousOptions,
} from './port-allocator.js';

export {
  slugifyBranch,
  worktreePath,
  verifyOwnership,
  assertOwnership,
  isExistingWorktree,
  WorktreeOwnershipError,
  type OwnershipResult,
} from './worktree.js';

export {
  WorktreePoolManager,
  WorktreePoolError,
  DEFAULT_POOL_ROOT,
  DEFAULT_STALE_THRESHOLD_DAYS,
  type WorktreePoolSpec,
  type WorktreePoolManagerDeps,
  type AllocateOptions,
  type WorktreeHandle,
} from './worktree-pool.js';

export {
  readParallelismMode,
  isParallelismEnabled,
  FLAG_NAME as PARALLELISM_FLAG,
  type ParallelismMode,
} from './parallelism-flag.js';

export { cleanGitEnv, gitExecFile } from './git-env.js';

export {
  ACCEPTED_SCHEMA_VERSIONS,
  ATTESTATION_ENVELOPE_PATH_PATTERN,
  CONTENTHASH_SHARED_CHURN_FILES,
  CONTENTHASHV4_IGNORE_FILES,
  DSSE_PAYLOAD_TYPE,
  INDEPENDENCE_REQUIRED_ROLES,
  REQUIRED_REVIEWER_AGENT_IDS,
  REVIEWER_ROLE_EQUIVALENCES,
  buildPredicate,
  collectChangedFileDeltaEntries,
  collectChangedFileEntries,
  collectChangedFileEntriesForV5,
  computeContentHash,
  computeContentHashV3,
  computeContentHashV4,
  computeContentHashV5,
  generateSigningKeyPair,
  isAttestationEnvelopePath,
  isIgnoredForContentHash,
  paeEncode,
  projectDeltaEntriesToHeadEntries,
  sha1Hex,
  sha256Hex,
  signAttestation,
  validatePredicateShape,
  validateTrustedReviewers,
  verifyAttestation,
  type AttestationPredicate,
  type BuildPredicateInputs,
  type ChangedFileDeltaEntry,
  type ChangedFileEntry,
  type ChangedFileHeadEntry,
  type ChangedFileV5Entry,
  type CollectChangedFileEntriesOptions,
  type DsseEnvelope,
  type DsseSignature,
  type ReviewerEntry,
  type SchemaVersion,
  type SubjectDigest,
  type TrustedReviewer,
  type V5CollectResult,
  type VerifyOptions,
  type VerifyResult,
} from './attestations.js';
