/**
 * Comprehensive type re-exports from @ai-sdlc/reference.
 * Ensures all reference types are accessible through the orchestrator package
 * for downstream consumers without direct reference dependency.
 */

// ── Core resource types ──────────────────────────────────────────────

export type {
  ApiVersion,
  Metadata,
  Condition,
  SecretRef,
  MetricCondition,
  Duration,
  Resource,
  TriggerFilter,
  Trigger,
  Provider,
  RoutingStrategy,
  ComplexityThreshold,
  Routing,
  Stage,
  PipelineSpec,
  PipelinePhase,
  PipelineStatus,
  Pipeline,
  AgentConstraints,
  HandoffContractRef,
  Handoff,
  SkillExample,
  Skill,
  AgentCard,
  AgentRoleSpec,
  AgentRoleStatus,
  AgentRole,
  GateScope,
  MetricRule,
  ToolRule,
  ReviewerRule,
  DocumentationRule,
  ProvenanceRule,
  ExpressionRule,
  GateRule,
  EnforcementLevel,
  Override,
  RetryPolicy,
  Evaluation,
  Gate,
  QualityGateSpec,
  QualityGateStatus,
  QualityGate,
  Permissions,
  ApprovalRequirement,
  Guardrails,
  MonitoringLevel,
  AutonomyLevel,
  PromotionCriteria,
  DemotionTrigger,
  AgentAutonomyStatus,
  AutonomyPolicySpec,
  AutonomyPolicyStatus,
  AutonomyPolicy,
  AdapterInterface,
  HealthCheck,
  AdapterBindingSpec,
  AdapterBindingStatus,
  AdapterBinding,
  // Design System Governance (RFC-0006)
  DesignToolAuthority,
  TokenFormat,
  TokenVersionPolicy,
  ConflictResolution,
  SyncDirection,
  OnTimeout,
  TokenPlatform,
  DesignReviewScope,
  DesignReviewAlwaysOn,
  DesignReviewCondition,
  AuthorityBlock,
  ChangeApproval,
  Stewardship,
  TokenSource,
  TokenSyncConfig,
  TokenConfig,
  CatalogSource,
  CatalogDiscovery,
  CatalogConfig,
  VisualRegressionProviderConfig,
  VisualRegressionConfig,
  HardcodedRule,
  CoverageThreshold,
  ComplianceConfig,
  DesignReviewTriggerCondition,
  DesignReviewTriggerConditions,
  DesignReviewConfig,
  DesignSystemBindingSpec,
  TokenSyncStatus,
  CatalogHealthStatus,
  TokenComplianceStatus,
  DesignReviewStatus,
  DesignSystemBindingStatus,
  DesignSystemBinding,
  AnyResource,
  ResourceKind,
  // Priority scoring (RFC-0005)
  PriorityPolicy,
  PriorityDimensionConfig,
  PriorityDimensionsConfig,
  PriorityCalibrationConfig,
  PriorityAdaptersConfig,
  // Design System Autonomy extensions (RFC-0006 §13)
  DesignSystemPermissions,
  DesignReviewRequirement,
  // Design System Pipeline/Agent extensions (RFC-0006 §6-7)
  StageConstraints,
  ContextStrategy,
  ContextStrategyOverride,
  ComponentCreationPolicy,
  AgentDesignSystemConfig,
  // Design System Gate Rules (RFC-0006 §8)
  DesignTokenComplianceRule,
  VisualRegressionRule,
  StoryCompletenessRule,
  DesignReviewDecision,
  DesignReviewFeedbackCategory,
  DesignReviewRating,
  DesignReviewFeedback,
  DesignReviewGateRule,
  // Validation (note: ValidationResult is not re-exported to avoid conflict with orchestrator's own)
  ValidationError,
} from '@ai-sdlc/reference';

// ── Policy types ─────────────────────────────────────────────────────

export type {
  GateVerdict,
  DemotionResult,
  ComplexityFactor,
  AuthorizationContext,
  AuthorizationResult,
  AuthIdentity,
  AuthenticationResult,
  Authenticator,
  MutatingGateContext,
  ExpressionEvaluator,
  ExpressionVerdict,
  LLMEvaluationDimension,
  LLMEvaluationResult,
  LLMGateVerdict,
} from '@ai-sdlc/reference';

// ── Agent types ──────────────────────────────────────────────────────

export type {
  AgentExecutionState,
  HandoffValidationError,
  SchemaResolver,
  SchemaValidationError,
  MemoryTier,
  MemoryEntry,
  WorkingMemory,
  ShortTermMemory,
  LongTermMemory,
  SharedMemory,
  EpisodicMemory,
} from '@ai-sdlc/reference';
